version: '3.4'
services:
  swoft:
    image: swoft/swoft
    #    for local develop
    #    command: php -S 127.0.0.1:13300
    container_name: swoft-srv
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "18306:18306"
      - "18307:18307"
      - "18308:18308"
    volumes:
      - ./:/var/www/swoft
      #       - ./:/var/www/swoft:delegated
      #      - ./:/var/www/swoft:cached
      # - ./runtime/ng-conf:/etc/nginx
      # - ./runtime/logs:/var/log

  mysql:
    image: mysql
    container_name: mysql-srv
    command: --default-authentication-plugin=mysql_native_password #这行代码解决无法访问的问题
    environment:
      MYSQL_ROOT_PASSWORD: ktp123123
    ports:
      - "13306:3306"
    volumes:
      - ./runtime/data/mysql:/var/lib/mysql
    restart: always

  redis:
    container_name: redis-srv
    image: redis:4-alpine
    command: /usr/local/bin/redis-server --requirepass redis123
    ports:
      - "16379:6379"
    sysctls:
      net.core.somaxconn: 65535
    restart: always
